steps:
  - id: 'build'
    name: 'earthly/earthly:v0.7.23'
    env:
      - "HOME=/root"
    args:
      - --allow-privileged
      - +docker
  
  - id: 'gcp-test'
    name: 'earthly/earthly:v0.7.23'
    env:
      - "HOME=/root"
    args:
      - +gcp-cloudbuild
    secretEnv:
      - 'EARTHLY_TOKEN'
    
availableSecrets:
  secretManager:
  - versionName: projects/earthly-jupyterlab/secrets/EARTHLY_TOKEN/versions/2
    env: 'EARTHLY_TOKEN'
